### ISSUE TITLE
 Create db table "wpt_provinces"

### ISSUE THREAD

**Issue by peixespnsc** [peixespnsc/speciesDatabase#12]
With the fields
- id
- name
- acronym
- id_country
- description
- note
- image
- published

**Comment by TNMedeiros** [comment]
The table "wpt_provinces" with the mentioned fields has been created.

**Comment by TNMedeiros** [comment]
I changed the "name" field to "varchar (63)" and the "acronym" field to "varchar (3)". It is more reasonable this way. The "varchar (63)" is to assure that all the countries' names can fit the space (inside 64 letters). The "varchar (3)" is a better option, because province acronyms are small words. Usually with only 2 or 3 letters.
